# service url
$URLS = %w(
aedash.adobe.com
arp.nd.edu
box.nd.edu
crashplan.nd.edu
crm.nd.edu
endeavor.nd.edu
gitlab-cswarm.crc.nd.edu
gmail.nd.edu
groups.nd.edu
http://comply.nd.edu
http://fixit.nd.edu
http://nd-1.ideascale.com
http://nd.compliance-assist.com
http://suspense-match.oit.nd.edu/
https://account.interfolio.com/sso
https://ace-database.nd.edu/ace/ancl/f?p=110
https://auxopsweb2.oit.nd.edu/idcardpin/
https://beat-test.nd.edu/
https://beat.nd.edu/
https://bxeprod.oit.nd.edu/StudentFacultyGradeEntry/ssb/gradeEntry
https://class-search-secure.nd.edu
https://cm.maxient.com/nd
https://cn157.awmdm.com/AirWatch/Login?GID=univ4202
https://cores-nd.mis.vanderbilt.edu/
https://datatransfer.nd.edu
https://departmentcharge.nd.edu/
https://digitalmedia.business.nd.edu/
https://dining-hall-tally.oit.nd.edu/
https://dmp.cdlib.org
https://dmptool.org/
https://e5.onthehub.com
https://enrollment.nd.edu/manage/
https://events.nd.edu/
https://facultyhistory.oit.nd.edu/
https://facultysetup.nd.edu/hrempmaintnew
https://ferpautility.nd.edu/
https://ferpawebcourse.nd.edu/index.cfm/
https://foapalinquiry.nd.edu/fin/foapal/
https://fysal.nd.edu/
https://geni.net
https://get.cbord.com/irish1card/full/login.php
https://go.mendoza.nd.edu/manage
https://gradconnect.nd.edu/
https://hathitrust.org
https://innopac.law.nd.edu/
https://irish1admin.oit.nd.edu/
https://irish1cardwebmanager.nd.edu/login/sso.php
https://irishcompass.nd.edu/
https://issalink.nd.edu
https://jenkins.library.nd.edu/jenkins
https://jobs.nd.edu/hr/shibboleth
https://ldc.nd.edu/
https://linuxmon-prod.dc.nd.edu/nagios
https://login.proxy.library.nd.edu
https://marcom.mendoza.nd.edu/contact-a-student/directory
https://marcomwiki.mendoza.nd.edu/
https://matchstick-test.cc.nd.edu/
https://matchstick.nd.edu/
https://mendoza.nd.edu
https://mybenefits.nd.edu
https://mystudentathletes.nd.edu
https://nd-test.hosted.panopto.com
https://nd.cayuse424.com
https://nd.cayuse424.com/sp/index.cfm
https://nd.keyusa.net/userLogin.do
https://nd.libapps.com/libapps/login.php
https://nd.medicatconnect.com/
https://nd.qualtrics.com
https://nd.starrezhousing.com/StarRezPortal/
https://nd.starrezhousing.com/StarRezWeb/
https://nd.starrezhousing.com/StarRezWebTest/
https://nd.uat.metricstream.com/
https://ndi-sa.nd.edu/
https://ndi-tr.nd.edu/
https://notredame.hosted.panopto.com
https://notredame.trackxnet.com
https://nscsss.nd.edu/
https://pa.nd.edu/
https://pulse1-prod.oit.nd.edu/PulseWebApp
https://sakainet.nd.edu/
https://secure.wisegateit.com
https://shib.everfi.net/login/default.aspx?id=unotredame
https://shibboleth-goirish-csm.symplicity.com/sso/
https://solutions.sciquest.com/apps/Router/SAMLAuth/NDProd
https://ssobnrprod.oit.nd.edu/ssomanager/
https://ssobnrprod.oit.nd.edu/ssomanager/c/SSB?pkg=http://ssb.oit.nd.edu/pls/BNRPROD/pzpkonad.p_start
https://tableau.nd.edu
https://tablemaint.nd.edu
https://travel.nd.edu
https://ultratime.nd.edu/UltraTime/
https://ultratime.nd.edu/utemob2/
https://universityofnotredame.skillport.com/
https://universityofnotredame.sumtotal.host
https://uw.nd.edu/login/login.html
https://wikispaces.psu.edu
https://www.digitalmeasures.com/login/nd-graduateschool/gradandPD
https://www.educause.edu/
https://www.globus.org/globus-connect
cilogon.org
https://www.journeyed.com/nd
https://www.workterra.net/admin
innotas.nd.edu
inside.nd.edu
irishcrm.my.salesforce.com
jenkins-cswarm.crc.nd.edu
learn-nexus.nd.edu
library.nd.edu/about/directory
m.nd.edu
mediaspace.nd.edu
ndclassifieds.nd.edu
ndi-sa.nd.edu
ndi-tr.nd.edu
nexus.nd.edu
osf.nd.edu
portal.office.com
remix.nd.edu
research.gov
sn.nd.edu
social-nexus.nd.edu
studio-nexus.nd.edu
theworknumber.nd.edu
wiki-cswarm.crc.nd.edu
www.citiprogram.org
www.xfinityoncampus.com
zoom.nd.edu
)
